// <auto-generated />
namespace Task_8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MyMigration01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyMigration01));
        
        string IMigrationMetadata.Id
        {
            get { return "201911231655269_My Migration 01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
